---
title: "Is 'Test & Release' Viable to Reopen Schools?"
author: "Kevin Kunzmann"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r r-setup, include=FALSE}
library(JuliaCall)
library(tidyverse)

knitr::opts_chunk$set(
	echo = FALSE,
	fig.width = 8,
	fig.height = 8/1.61
)
```

```{julia julia-setup, include=FALSE}
import Pkg; Pkg.activate(".julia")
using Distributed
addprocs(Sys.CPU_THREADS)
@everywhere begin
	import Pkg
	Pkg.activate(".julia")
	Pkg.instantiate()
	using cov19sim
end # @everywhere
```



# Problem Statement

# Population Model for School

# Calibrating Infectivity

# Evaluating Performance

# Results

```{julia, results="hide"}
@everywhere begin 

function f(i)
    school = ThreeLevelPopulation(policy_bubble = SymptomaticIsolation(14, true))
    infect!.(school.individuals[1])
    steps!(school, 80)
    evaluate(school)
end

end #@everywhere
tbl_res = vcat(pmap(f, 1:50)...)
```

```{r}
library(JuliaCall)
library(tidyverse)
julia_eval("tbl_res") %>% as_tibble()
```

